### ISSUE TITLE
Paleta e logo

### ISSUE THREAD

**Issue by johnylab** [CopaTecnologia/copatecnologia.github.io#1]
![copa pallete color palette - color-hex com](https://cloud.githubusercontent.com/assets/1944417/25438274/4df1cb86-2a6f-11e7-8a8e-8d3918175569.png)

http://www.color-hex.com/color-palette/37530

Colors in Palette (hex / rgb)
#ff8800	(255,136,0)
#dcdedd	(220,222,221)
#99a2a1	(153,162,161)
#00585a	(0,88,90)
#001e22	(0,30,34)

**Comment by aleamparo** [comment]
![copa_logo_1](https://cloud.githubusercontent.com/assets/26008151/25439857/035663e8-2a74-11e7-8f87-1adc71b51c59.png)

**Comment by johnylab** [comment]
Qual é essa fonte?

**Comment by aleamparo** [comment]
[Quantify v2.3.zip](https://github.com/CopaTecnologia/copatecnologia.github.io/files/958746/Quantify.v2.3.zip)

**Comment by johnylab** [comment]
Pelo visto, pelo menos o kern dela é bom. Você viu se ela tem acentos?

**Comment by aleamparo** [comment]
![copa_logo_2](https://cloud.githubusercontent.com/assets/26008151/25440271/599713f0-2a75-11e7-83de-115facf63bd3.png)

Versão acrônimo

**Comment by aleamparo** [comment]
Não possui acentuação. Exceto o til solto.
Texto cinza em helvetica.
[HelveticaCdHv.ttf.zip](https://github.com/CopaTecnologia/copatecnologia.github.io/files/958831/HelveticaCdHv.ttf.zip)

**Comment by johnylab** [comment]
Esse texto ficaria melhor sem preposiçoes:

CRIATIVIDADE
ORGANIZAÇÃO
PROCESSOS
APRENDIZAGEM

**Comment by johnylab** [comment]
https://copatecnologia.github.io/

**Comment by Johnylab** [comment]
![snapshot 2017-04-26 17h09](https://cloud.githubusercontent.com/assets/1944417/25454545/30acc79a-2aa3-11e7-87f3-7aeb1102fd71.png)

**Comment by aleamparo** [comment]
![copa_logo_3](https://cloud.githubusercontent.com/assets/26008151/25527539/87cd3008-2bef-11e7-95b7-ddc82dc388bb.png)

**Comment by aleamparo** [comment]
![copa_logo_7](https://cloud.githubusercontent.com/assets/26008151/25544542/52a7c342-2c31-11e7-8b54-fed1ef4a4939.png)

**Comment by aleamparo** [comment]
[trench.zip](https://github.com/CopaTecnologia/copatecnologia.github.io/files/1088611/trench.zip)

Texto: COPA (usei contorno, por ser muito light, de 0,2mm)

**Comment by aleamparo** [comment]
![copa_cardf](https://user-images.githubusercontent.com/26008151/27340558-2607dc6a-55b1-11e7-9c79-d53ee35f793a.jpg)

**Comment by johnylab** [comment]
O logo parece que já está ok por enquanto. Estou encerrando esta issue.

Vamos passar a paleta a limpo em [uma conversa nova](https://github.com/CopaTecnologia/copatecnologia.github.io/issues/5).
