### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by johnylab** [CopaTecnologia/copatecnologia.github.io#2]
![snapshot 2017-04-26 17h09](https://cloud.githubusercontent.com/assets/1944417/25454618/7c21c18a-2aa3-11e7-8a60-ef4fb391c581.png)

**Comment by johnylab** [comment]
Acho que faltam as informações. Texto

- Veja mais fotos no Drive
- Escolher umas fontes: https://fonts.google.com/

**Comment by aleamparo** [comment]
best education website design
https://goo.gl/fXwjQB

Esse site aparece em um dos resultados da pesquisa acima: https://vestibular.imed.edu.br/

**Comment by johnylab** [comment]
Parallax eu acho mais ou menos, mas tem esse efeito que as coisas aparecem depois que rola, que eu acho bem legal.

**Comment by johnylab** [comment]
Vídeos:

- [Camera Lens](https://www.youtube.com/watch?v=oC5qQC1_3Ho) (oC5qQC1_3Ho)
- [Typing Web Addresses](https://www.youtube.com/watch?v=rSdaUzZ6Ero) (rSdaUzZ6Ero)

**Comment by johnylab** [comment]
Sobre o [coverr](http://www.coverr.co/), não achei nada que pareça relevante.

**Comment by johnylab** [comment]
Gostei desse:

> [Camera Lens](https://www.youtube.com/watch?v=oC5qQC1_3Ho)

Onde usar? No rodapé? No topo? Em uma página interna?

**Comment by johnylab** [comment]
![joxi_screenshot_1498138666323](https://user-images.githubusercontent.com/1944417/27436858-e2218c4e-5736-11e7-9214-5313c96e5e2d.png)
