### ISSUE TITLE
Textos

### ISSUE THREAD

**Issue by aleamparo** [CopaTecnologia/copatecnologia.github.io#3]
A COPA TECNOLOGIA foi fundada a partir da parceria entre profissionais das áreas da educação, comunicação e tecnologia, com o objetivo de atender instituições de ensino, empresas e profissionais, no desenvolvimento de soluções educacionais, corporativas e de comunicação.

A COPA entende que cada cliente possui uma identidade própria, um nível diferenciado de competências, planos e objetivos de desenvolvimento. Por esta razão, soluções customizadas construídas junto com o cliente, são aquelas que melhor atendem às suas demandas de desenvolvimento específicas.

**Comment by aleamparo** [comment]
O uso correto das tecnologias é parte fundamental para que os objetivos sejam alcançados. Sendo assim, a COPA propõe ferramentas de comprovada eficácia, baseada na experiência e nos resultados alcançados ao longo da trajetória profissional de nossa equipe.

**Comment by aleamparo** [comment]
PRODUÇÃO AUDIOVISUAL
Videoaulas educativas;
Vídeos para treinamento e reciclagem de colaboradores;
Vídeos Institucionais;
Cobertura de eventos educacionais e corporativos;
Edição de vídeos;
Edição e mixagem de áudios.

PRODUÇÃO EDITORIAL
Materiais didáticos em formato de texto;
Manuais;
Revistas;
Periódicos.

DESENVOLVIMENTO WEB
Sites;
Hotsites;
Blogs;
Newsletters;
Formulários de pesquisas estatísticas;
Sistema de busca em bancos de recursos tecnológicos;
Aplicativos de apoio pedagógico;
Galerias de arte online;

COMUNICAÇÃO
Mídias Sociais.
Branding;
Marketing;
Endomarketing;
Mobile marketing;
Design gráfico;

**Comment by Johnylab** [comment]
![localhost-3000-](https://cloud.githubusercontent.com/assets/1944417/26271814/98d3fc3a-3ce1-11e7-9cb9-bf3a0a4ea2b3.png)

**Comment by johnylab** [comment]
![localhost-3000-](https://cloud.githubusercontent.com/assets/1944417/26271845/e33d33fe-3ce1-11e7-9ac4-38a2ff3884cc.png)

**Comment by johnylab** [comment]
Coloquei a fonte Share Tech nos títulos [https://copatecnologia.github.io/](https://copatecnologia.github.io/)

**Comment by johnylab** [comment]
Site do Github Pages linkado no domínio principal [copatecnologia.com.br](http://copatecnologia.com.br)

**Comment by johnylab** [comment]
Falta uma frase de efeito no topo e o texto que aparece na busca do Google (e no rodapé).

**Comment by aleamparo** [comment]
A parte COMUNICAÇÃO vc suprimiu do site?

**Comment by johnylab** [comment]
Eu estava tentando fazer caber. Vou tentar de novo depois.

Em 21/05/2017 12:10 PM, Alexandre Amparo <notifications@github.com> escreveu:

A parte COMUNICAÇÃO vc suprimiu do site?

**Comment by aleamparo** [comment]
Endendi! ;)
